name: Rename Application ID


on:
  push:
    branches:
      - main

jobs:
  rename_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install rename package
        run: flutter pub global activate rename

      - name: Rename Application ID
        run: |
          NEW_APP_ID="com.dix.new"
          rename setBundleId --value "$NEW_APP_ID"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated: Rename application ID to $NEW_APP_ID" || echo "No changes to commit"
          

      - name: Change Colors in Dart Code (AppTheme)
        run: |
          PRIMARY_COLOR="0xff007bff"  # Your new primary color (hex)
          SECONDARY_COLOR="0xffdc3545" # Your new secondary color (hex)

          # Example using `sed` to replace color values in a Dart file.
          # Adapt the file path (lib/infrastructure/theme/theme.dart) and the regexes to match your code.
          sed -i "s/Color(0xFF00A3E0)/Color($PRIMARY_COLOR)/g" lib/infrastructure/theme/theme.dart
          sed -i "s/Color(0xFF13a1db)/Color($SECONDARY_COLOR)/g" lib/infrastructure/theme/theme.dart

      - name: Push Changes
        run: |
          git config --global url."https://${{ secrets.MY_GIT_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git push origin HEAD:refs/heads/main
        shell: /usr/bin/bash -e {0}
        env:
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.29.0-x64
          PUB_CACHE: /home/runner/.pub-cache