name: Rename Application ID for Android & iOS

on:
  push:
    branches:
      - main

jobs:
  rename_app_id:
    runs-on: macos-latest  # Required for iOS builds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Replace with your Flutter version

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Set Environment Variables
        run: |
          echo "NEW_APP_ID=com.dix.new" >> $GITHUB_ENV
          echo "NEW_BUNDLE_ID=com.dix.new" >> $GITHUB_ENV

      - name: Rename Application ID (Android)
        run: |
          sed -i '' 's/applicationId "com.old.app"/applicationId "'"$NEW_APP_ID"'"/g' android/app/build.gradle

      - name: Rename Bundle Identifier (iOS)
        run: |
          sed -i '' 's/com.old.app/'"$NEW_BUNDLE_ID"'/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Verify Changes
        run: |
          grep "applicationId" android/app/build.gradle || echo "Application ID not found"
          grep -A3 "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj || echo "Bundle ID not found"

      - name: Build Debug APK (Android)
        run: |
          cd android
          chmod +x gradlew  # Ensure gradlew is executable
          ./gradlew assembleDebug

      - name: Build iOS App
        run: |
          cd ios
          pod install
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Debug
