name: Rename Application ID

on:
  # Choose when this action runs.  Examples:
  # Manually:
  workflow_dispatch:
  # On push to a specific branch:
  # push:
  #   branches: [main]

jobs:
  rename_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3' # Or your specific version
          channel: 'stable'

      - name: Install rename package
        run: flutter pub global activate rename

      - name: Rename Application ID
        run: |
          NEW_APP_ID="com.dash.new" # Your new application ID
          rename setBundleId --value "$NEW_APP_ID"
          # Commit the changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .  # Add all changed files
          git commit -m "Automated: Rename application ID to $NEW_APP_ID" || echo "No changes to commit" # Handle no changes
          git push origin HEAD:${{ github.ref }} # Push the changes

      # Optional: Run Flutter build to verify (after rename)
      # - name: Build Flutter app (optional)
      #   run: flutter build apk --release # Or other build command