name: Update Application ID

on: [push]

jobs:
  update-application-id:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: List directory contents
      run: ls -la android/

    - name: Update applicationId in build.gradle
      run: |
        sed -i 's/applicationId "com.dix.new"/applicationId "com.example.newid"/' android/app/build.gradle

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build with Gradle
      run: android/gradlew build
