name: Build Flutter APK & iOS IPA with New App ID

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3

      - name: Rename Application ID (Android) and Bundle ID (iOS)
        run: |
          OLD_APP_ID="com.dix.new"
          NEW_APP_ID="com.example.newid"

          # ✅ Change applicationId in Android build.gradle
          sed -i "s/applicationId \"$OLD_APP_ID\"/applicationId \"$NEW_APP_ID\"/g" android/app/build.gradle

          # ✅ Change bundle identifier in iOS project.pbxproj
          sed -i "s/$OLD_APP_ID/$NEW_APP_ID/g" ios/Runner.xcodeproj/project.pbxproj

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS (Requires macOS)
        if: runner.os == 'macOS'
        run: |
          cd ios
          pod install
          flutter build ios --release
