name: Rename Application ID


on:
  push:
    branches:
      - main

jobs:
  rename_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install rename package
        run: flutter pub global activate rename

      - name: Rename Application ID
        run: |
          NEW_APP_ID="com.dash.new"
          rename setBundleId --value "$NEW_APP_ID"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated: Rename application ID to $NEW_APP_ID" || echo "No changes to commit"

      - name: Push Changes  # Fixed push command
        run: |
          git config --global url."https://${{ secrets.My_git_token }}@github.com/".insteadOf "https://github.com/"
          git push origin HEAD:${{ github.ref }}