name: Generate Keystore & Build APK

on:
  push:
    branches:
      - main

jobs:
  generate-keystore-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify gradlew Exists
        run: ls -la android

      - name: Set Execute Permission for gradlew
        run: chmod +x android/gradlew

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Keystore File
        run: |
          keytool -genkeypair -v \
            -keystore android/app/generated-keystore.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias my-key-alias \
            -storepass my-keystore-password \
            -keypass my-key-password \
            -dname "CN=Your Name, OU=Your Org, O=Your Company, L=Your City, S=Your State, C=Your Country"

      - name: Save Keystore as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-keystore
          path: android/app/generated-keystore.jks

      - name: Build Release APK
        env:
          ANDROID_KEYSTORE_PATH: android/app/generated-keystore.jks
          ANDROID_KEYSTORE_PASSWORD: my-keystore-password
          ANDROID_KEY_ALIAS: my-key-alias
          ANDROID_KEY_PASSWORD: my-key-password
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
