name: Rename Application ID

on:
  push:
    branches:
      - main

jobs:
  rename_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install rename package
        run: flutter pub global activate rename

      - name: Rename Application ID
        run: |
          NEW_APP_ID="com.dixTest.new"
          rename setBundleId --value "$NEW_APP_ID"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated: Rename application ID to $NEW_APP_ID" || echo "No changes to commit"


      - name: Set Color Variables
        run: |
          PRIMARY_COLOR="0xff007bff"
          SECONDARY_COLOR="0xffdc3545"
          echo "PRIMARY_COLOR=$PRIMARY_COLOR" >> $GITHUB_ENV
          echo "SECONDARY_COLOR=$SECONDARY_COLOR" >> $GITHUB_ENV

      - name: Change Colors in Dart Code (AppTheme)
        run: |
          FILE_PATH="lib/infrastructure/theme/theme.dart"
          if [ -f "$FILE_PATH" ]; then
            echo "File found: $FILE_PATH"
            sed -i "s/final Color primary = const Color(0xFF00A3E0);/final Color primary = const Color(\"${{ env.PRIMARY_COLOR }}\");/gI" "$FILE_PATH"
            sed -i "s/final Color secondary = Color(0xFF13a1db);/final Color secondary = Color(\"${{ env.SECONDARY_COLOR }}\");/gI" "$FILE_PATH"
            cat "$FILE_PATH" # Debugging: Print file contents
          else
            echo "File not found: $FILE_PATH"
            exit 1
          fi

      - name: Push Changes
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/" # Use GITHUB_TOKEN
          git push origin HEAD:${{ github.ref }} # Use github.ref